/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Events;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Home.HomeFinalOne;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Naseef Nazz
 */
public class EventsFinalOne extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    Statement stmt=null;
    
    public EventsFinalOne() {
        initComponents();
        
        conn=DbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        Fixtures = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txt_round = new javax.swing.JTextField();
        txt_vs = new javax.swing.JTextField();
        txt_hme = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        AddFixtures = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_time = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_place = new javax.swing.JTextField();
        Events = new javax.swing.JPanel();
        txt_when = new javax.swing.JTextField();
        txt_event = new javax.swing.JTextField();
        txt_where = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        addEvent = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Side_Pane = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        league = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLevents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1368, 746));
        setMinimumSize(new java.awt.Dimension(1368, 746));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1368, 659));
        jPanel1.setMinimumSize(new java.awt.Dimension(1368, 659));
        jPanel1.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(71, 120, 197));
        jPanel9.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(120, 168, 252));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIXTURES & EVENTS");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 250, 30);

        jPanel9.add(jPanel3);
        jPanel3.setBounds(0, 0, 490, 50);

        parentPanel.setBackground(new java.awt.Color(71, 120, 197));
        parentPanel.setName("parentPanel"); // NOI18N
        parentPanel.setOpaque(false);
        parentPanel.setLayout(new java.awt.CardLayout());

        Fixtures.setOpaque(false);
        Fixtures.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Round");
        Fixtures.add(jLabel27);
        jLabel27.setBounds(30, 40, 90, 20);

        txt_round.setBackground(new java.awt.Color(71, 120, 197));
        txt_round.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_round.setForeground(new java.awt.Color(255, 255, 255));
        txt_round.setOpaque(false);
        txt_round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roundActionPerformed(evt);
            }
        });
        Fixtures.add(txt_round);
        txt_round.setBounds(140, 30, 320, 30);

        txt_vs.setBackground(new java.awt.Color(71, 120, 197));
        txt_vs.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_vs.setForeground(new java.awt.Color(255, 255, 255));
        txt_vs.setOpaque(false);
        txt_vs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vsActionPerformed(evt);
            }
        });
        Fixtures.add(txt_vs);
        txt_vs.setBounds(140, 130, 320, 30);

        txt_hme.setBackground(new java.awt.Color(71, 120, 197));
        txt_hme.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_hme.setForeground(new java.awt.Color(255, 255, 255));
        txt_hme.setOpaque(false);
        txt_hme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hmeActionPerformed(evt);
            }
        });
        Fixtures.add(txt_hme);
        txt_hme.setBounds(140, 280, 320, 30);

        jButton2.setBackground(new java.awt.Color(71, 120, 197));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Fixtures.add(jButton2);
        jButton2.setBounds(290, 360, 110, 40);

        jButton5.setBackground(new java.awt.Color(71, 120, 197));
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Fixtures.add(jButton5);
        jButton5.setBounds(160, 360, 110, 40);

        AddFixtures.setBackground(new java.awt.Color(71, 120, 197));
        AddFixtures.setText("Add Fixtures");
        AddFixtures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFixturesActionPerformed(evt);
            }
        });
        Fixtures.add(AddFixtures);
        AddFixtures.setBounds(30, 360, 110, 40);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Date");
        Fixtures.add(jLabel29);
        jLabel29.setBounds(30, 90, 90, 20);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("VS");
        Fixtures.add(jLabel30);
        jLabel30.setBounds(30, 140, 90, 20);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("HME");
        Fixtures.add(jLabel31);
        jLabel31.setBounds(30, 290, 90, 20);

        txt_date.setBackground(new java.awt.Color(71, 120, 197));
        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_date.setForeground(new java.awt.Color(255, 255, 255));
        txt_date.setOpaque(false);
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        Fixtures.add(txt_date);
        txt_date.setBounds(140, 80, 320, 30);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Time");
        Fixtures.add(jLabel32);
        jLabel32.setBounds(30, 240, 90, 20);

        txt_time.setBackground(new java.awt.Color(71, 120, 197));
        txt_time.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_time.setForeground(new java.awt.Color(255, 255, 255));
        txt_time.setOpaque(false);
        txt_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeActionPerformed(evt);
            }
        });
        Fixtures.add(txt_time);
        txt_time.setBounds(140, 230, 320, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Where");
        Fixtures.add(jLabel33);
        jLabel33.setBounds(30, 190, 90, 20);

        txt_place.setBackground(new java.awt.Color(71, 120, 197));
        txt_place.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_place.setForeground(new java.awt.Color(255, 255, 255));
        txt_place.setOpaque(false);
        txt_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placeActionPerformed(evt);
            }
        });
        Fixtures.add(txt_place);
        txt_place.setBounds(140, 180, 320, 30);

        parentPanel.add(Fixtures, "card2");

        Events.setOpaque(false);
        Events.setLayout(null);

        txt_when.setBackground(new java.awt.Color(71, 120, 197));
        txt_when.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_when.setForeground(new java.awt.Color(255, 255, 255));
        txt_when.setOpaque(false);
        txt_when.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_whenActionPerformed(evt);
            }
        });
        Events.add(txt_when);
        txt_when.setBounds(140, 30, 320, 30);

        txt_event.setBackground(new java.awt.Color(71, 120, 197));
        txt_event.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_event.setForeground(new java.awt.Color(255, 255, 255));
        txt_event.setOpaque(false);
        txt_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_eventActionPerformed(evt);
            }
        });
        Events.add(txt_event);
        txt_event.setBounds(140, 80, 320, 30);

        txt_where.setBackground(new java.awt.Color(71, 120, 197));
        txt_where.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_where.setForeground(new java.awt.Color(255, 255, 255));
        txt_where.setOpaque(false);
        txt_where.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_whereActionPerformed(evt);
            }
        });
        Events.add(txt_where);
        txt_where.setBounds(140, 130, 320, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("When");
        Events.add(jLabel34);
        jLabel34.setBounds(30, 40, 90, 20);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Event");
        Events.add(jLabel35);
        jLabel35.setBounds(30, 90, 90, 20);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Where");
        Events.add(jLabel36);
        jLabel36.setBounds(30, 140, 90, 20);

        addEvent.setBackground(new java.awt.Color(71, 120, 197));
        addEvent.setText("Add Events");
        addEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventActionPerformed(evt);
            }
        });
        Events.add(addEvent);
        addEvent.setBounds(30, 210, 110, 40);

        jButton8.setBackground(new java.awt.Color(71, 120, 197));
        jButton8.setText("View");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Events.add(jButton8);
        jButton8.setBounds(160, 210, 110, 40);

        jButton9.setBackground(new java.awt.Color(71, 120, 197));
        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Events.add(jButton9);
        jButton9.setBounds(290, 210, 110, 40);

        parentPanel.add(Events, "card2");

        jPanel9.add(parentPanel);
        parentPanel.setBounds(0, 50, 490, 590);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(190, 30, 490, 720);

        Side_Pane.setBackground(new java.awt.Color(23, 35, 51));
        Side_Pane.setLayout(null);

        btn_1.setBackground(new java.awt.Color(41, 57, 80));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });
        btn_1.setLayout(null);

        jPanel12.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_1.add(jPanel12);
        jPanel12.setBounds(0, 0, 3, 44);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Fixtures");
        btn_1.add(jLabel8);
        jLabel8.setBounds(46, 16, 80, 15);

        Side_Pane.add(btn_1);
        btn_1.setBounds(0, 80, 190, 44);

        btn_2.setBackground(new java.awt.Color(23, 35, 51));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
        });
        btn_2.setLayout(null);

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_2.add(jPanel13);
        jPanel13.setBounds(0, 0, 3, 44);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Add Events");
        btn_2.add(jLabel9);
        jLabel9.setBounds(46, 13, 70, 15);

        Side_Pane.add(btn_2);
        btn_2.setBounds(0, 140, 190, 44);

        jPanel1.add(Side_Pane);
        Side_Pane.setBounds(0, 0, 190, 750);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(190, 0, 490, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(71, 120, 197));
        jLabel17.setText("2019 UNITED SC MEN'S LEAGUE FIXTURES");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(710, 40, 570, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(710, 680, 130, 40);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        league.setBackground(new java.awt.Color(246, 240, 240));
        league.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ROUND", "DATE", "VS", "WHERE", "TIME", "HOME MATCH EVENTS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        league.setGridColor(new java.awt.Color(255, 255, 255));
        league.setRowHeight(25);
        league.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(league);
        if (league.getColumnModel().getColumnCount() > 0) {
            league.getColumnModel().getColumn(0).setMinWidth(60);
            league.getColumnModel().getColumn(0).setPreferredWidth(60);
            league.getColumnModel().getColumn(0).setMaxWidth(60);
            league.getColumnModel().getColumn(1).setMinWidth(160);
            league.getColumnModel().getColumn(1).setPreferredWidth(160);
            league.getColumnModel().getColumn(1).setMaxWidth(160);
            league.getColumnModel().getColumn(2).setMinWidth(80);
            league.getColumnModel().getColumn(2).setPreferredWidth(80);
            league.getColumnModel().getColumn(2).setMaxWidth(80);
            league.getColumnModel().getColumn(3).setMinWidth(60);
            league.getColumnModel().getColumn(3).setPreferredWidth(60);
            league.getColumnModel().getColumn(3).setMaxWidth(60);
            league.getColumnModel().getColumn(4).setMinWidth(55);
            league.getColumnModel().getColumn(4).setPreferredWidth(55);
            league.getColumnModel().getColumn(4).setMaxWidth(55);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(710, 100, 630, 230);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/close2.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1320, 0, 50, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/minimize2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1270, 0, 50, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(71, 120, 197));
        jLabel18.setText("CLUB EVENTS");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(710, 370, 570, 30);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbLevents.setBackground(new java.awt.Color(246, 240, 240));
        tbLevents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbLevents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "WHEN", "EVENT", "WHERE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLevents.setGridColor(new java.awt.Color(255, 255, 255));
        tbLevents.setRowHeight(25);
        jScrollPane3.setViewportView(tbLevents);
        if (tbLevents.getColumnModel().getColumnCount() > 0) {
            tbLevents.getColumnModel().getColumn(0).setMinWidth(160);
            tbLevents.getColumnModel().getColumn(0).setPreferredWidth(160);
            tbLevents.getColumnModel().getColumn(0).setMaxWidth(160);
            tbLevents.getColumnModel().getColumn(2).setMinWidth(100);
            tbLevents.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbLevents.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(710, 430, 630, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new HomeFinalOne().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/closeIn.jpg"));
        jLabel6.setIcon(II);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/close2.png"));
        jLabel6.setIcon(II);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimizeIn.jpg"));
        jLabel4.setIcon(II2);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimize2.png"));
        jLabel4.setIcon(II2);
    }//GEN-LAST:event_jLabel4MouseExited

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        setColor(btn_1);
        jPanel12.setOpaque(true);
        resetColor(new JPanel[]{btn_2}, new JPanel[]{jPanel13});

        parentPanel.removeAll();
        parentPanel.add(Fixtures);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        setColor(btn_2);
        jPanel13.setOpaque(true);
        resetColor(new JPanel[]{btn_1}, new JPanel[]{jPanel12});

        parentPanel.removeAll();
        parentPanel.add(Events);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_2MousePressed

    private void txt_roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roundActionPerformed

    private void txt_vsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vsActionPerformed

    private void txt_hmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hmeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{
        
            //conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/club_management?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","");
            
            String showTable;
            
            showTable="SELECT * FROM `league_fixtures`";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            league.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AddFixturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFixturesActionPerformed
       
        try{
            
            String addFixtures;
            
            addFixtures= "INSERT INTO `league_fixtures`(`fix_round`, `fix_date`, `fix_opponent`, `fix_where`, `fix_time`, `fix_hme`) VALUES (?,?,?,?,?,? ) " ;
            
            pst=conn.prepareStatement(addFixtures);
            
            pst.setString(1,txt_round.getText());
            pst.setString(2,txt_date.getText());
            pst.setString(3,txt_vs.getText());
            pst.setString(4,txt_place.getText());
            pst.setString(5,txt_time.getText());
            pst.setString(6,txt_hme.getText());
            
            pst.executeUpdate();
         
            JOptionPane.showMessageDialog(null,"Addedd !");
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_AddFixturesActionPerformed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateActionPerformed

    private void txt_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeActionPerformed

    private void txt_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placeActionPerformed

    private void txt_whenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_whenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_whenActionPerformed

    private void txt_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_eventActionPerformed

    private void txt_whereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_whereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_whereActionPerformed

    private void addEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventActionPerformed
       
        try{
            
            String addEvents;
            
            addEvents= "INSERT INTO `league_events`(`WHEN`, `EVENT`, `WHERE`) VALUES (?,?,?) " ;
            
            pst=conn.prepareStatement(addEvents);
            
            pst.setString(1,txt_when.getText());
            pst.setString(2,txt_event.getText());
            pst.setString(3,txt_where.getText());
            
            
            pst.executeUpdate();
         
            JOptionPane.showMessageDialog(null,"Addedd !");
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
    }//GEN-LAST:event_addEventActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
       try{
        
            //conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/club_management?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","");
            
            String showTable2;
            
            showTable2="SELECT * FROM `league_events`";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable2);
            
            
            //please code to view details when the frame opened
            //code works
            tbLevents.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsFinalOne().setVisible(true);
            }
        });
    }
    
    
        private void setColor(JPanel pane)
        {
            pane.setBackground(new Color(41,57,80));
        }
        
        private void resetColor(JPanel [] pane, JPanel [] indicators)
        { 
            for(int i=0;i<pane.length;i++)
            {
            pane[i].setBackground(new Color(23,35,51));
            }
            
            for(int i=0;i<indicators.length;i++)
            {
            indicators[i].setOpaque(false);
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFixtures;
    private javax.swing.JPanel Events;
    private javax.swing.JPanel Fixtures;
    private javax.swing.JPanel Side_Pane;
    private javax.swing.JButton addEvent;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable league;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTable tbLevents;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_event;
    private javax.swing.JTextField txt_hme;
    private javax.swing.JTextField txt_place;
    private javax.swing.JTextField txt_round;
    private javax.swing.JTextField txt_time;
    private javax.swing.JTextField txt_vs;
    private javax.swing.JTextField txt_when;
    private javax.swing.JTextField txt_where;
    // End of variables declaration//GEN-END:variables
}
