/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SignUp;


import Home.HomeFinalOne;
import Login.LoginFinalOne;
import TransferPlayer.DbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Naseef Nazz
 */
public class SignUpFinalOne extends javax.swing.JFrame {

    
      Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    public SignUpFinalOne() {
        initComponents();
        
        conn=DbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        createAccount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uCombo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        uPassword = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        accName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        uAnswer = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(858, 755));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        createAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUp/signupBttn.png"))); // NOI18N
        createAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountMouseClicked(evt);
            }
        });
        jPanel4.add(createAccount);
        createAccount.setBounds(90, 650, 240, 40);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 184, 197));
        jLabel9.setText("CLUB MANAGEMENT SYSTEM");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(110, 710, 208, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(41, 184, 194));
        jLabel14.setText("SIGNUP");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(150, 40, 140, 60);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(41, 184, 194));
        jLabel7.setText("SEQURITY QUETION");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(60, 450, 180, 29);

        uCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Favorite Colour?", "Favorite Country?", "Favorite Language?" }));
        uCombo.setBorder(null);
        uCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uComboActionPerformed(evt);
            }
        });
        uCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                uComboPropertyChange(evt);
            }
        });
        jPanel4.add(uCombo);
        uCombo.setBounds(60, 480, 290, 40);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(41, 184, 194));
        jLabel19.setText("USERNAME");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(60, 230, 101, 22);

        uName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        uName.setBorder(null);
        uName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                uNameMouseMoved(evt);
            }
        });
        jPanel4.add(uName);
        uName.setBounds(60, 270, 280, 30);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(60, 300, 280, 10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/username3.png"))); // NOI18N
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 270, 30, 40);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(41, 184, 194));
        jLabel20.setText("PASSWORD");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(60, 330, 104, 22);

        uPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        uPassword.setBorder(null);
        uPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                uPasswordMouseMoved(evt);
            }
        });
        jPanel4.add(uPassword);
        uPassword.setBounds(60, 370, 280, 30);
        jPanel4.add(jSeparator5);
        jSeparator5.setBounds(60, 400, 280, 10);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/password2.png"))); // NOI18N
        jPanel4.add(jLabel12);
        jLabel12.setBounds(20, 370, 30, 40);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(41, 184, 194));
        jLabel21.setText("NAME");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(60, 130, 51, 22);

        accName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accName.setBorder(null);
        accName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                accNameMouseMoved(evt);
            }
        });
        jPanel4.add(accName);
        accName.setBounds(60, 170, 280, 30);
        jPanel4.add(jSeparator6);
        jSeparator6.setBounds(60, 200, 280, 10);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(41, 184, 194));
        jLabel22.setText("ANSWER");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(60, 540, 78, 22);

        uAnswer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        uAnswer.setBorder(null);
        uAnswer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                uAnswerMouseMoved(evt);
            }
        });
        jPanel4.add(uAnswer);
        uAnswer.setBounds(60, 580, 280, 30);
        jPanel4.add(jSeparator7);
        jSeparator7.setBounds(60, 610, 280, 10);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/minimize2.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel4.add(jLabel5);
        jLabel5.setBounds(330, 0, 50, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/close2.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel4.add(jLabel6);
        jLabel6.setBounds(380, 0, 50, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(430, 0, 430, 755);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUp/club logo 4.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(100, 340, 240, 250);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UNITED FOOTBALL CLUB");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 640, 220, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUp/left cover.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 430, 755);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 760);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_uComboPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_uComboPropertyChange

    private void uComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uComboActionPerformed

    private void createAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountMouseClicked
        
        
        
        
          try {
        
            String query;
            query = "INSERT INTO `admin`(`name`, `user_name`, `user_password`, `sec_question`, `q_answer`) VALUES (?,?,?,?,?)";
            
            
                
           // conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/club_management?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","");
            
            pst=conn.prepareStatement(query);
            
            pst.setString(1,accName.getText());
            pst.setString(2,uName.getText());
            pst.setString(3,uPassword.getText());
            pst.setString(4,uCombo.getSelectedItem().toString());
            pst.setString(5,uAnswer.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Account Has been Created");
            
          
            accName.setText("");
            uName.setText("");
            uPassword.setText("");
            uAnswer.setText("");
            
            
            
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
          // Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_createAccountMouseClicked

    private void uNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uNameMouseMoved

    }//GEN-LAST:event_uNameMouseMoved

    private void uPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uPasswordMouseMoved

    }//GEN-LAST:event_uPasswordMouseMoved

    private void accNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_accNameMouseMoved

    private void uAnswerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uAnswerMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_uAnswerMouseMoved

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimizeIn.jpg"));
        jLabel5.setIcon(II2);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimize2.png"));
        jLabel5.setIcon(II2);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
      
        new HomeFinalOne().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/closeIn.jpg"));
        jLabel6.setIcon(II);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/close2.png"));
        jLabel6.setIcon(II);
    }//GEN-LAST:event_jLabel6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFinalOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accName;
    private javax.swing.JLabel createAccount;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField uAnswer;
    private javax.swing.JComboBox uCombo;
    private javax.swing.JTextField uName;
    private javax.swing.JTextField uPassword;
    // End of variables declaration//GEN-END:variables
}
