/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WholeSquad;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Home.HomeFinalOne;
import RemovePlayer.RemovePlayerFinalOne;
import UpdatePlayer.DbConnection;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Naseef Nazz
 */
public class WholeSquadFinalOne extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    public WholeSquadFinalOne() {
        initComponents();
         conn=DbConnection.connect();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        squad = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        parentPanel = new javax.swing.JPanel();
        ForwadPlayer = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        forward = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Defenders = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        defenders = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        RightWingers = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        rightWing = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        MidFiealders = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        mid = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        LeftWingers = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        leftwing = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        GoalKeepers = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        goalKeeper = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Side_Pane = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        squadRefresh = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1368, 746));
        setMinimumSize(new java.awt.Dimension(1368, 746));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1368, 746));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1368, 659));
        jPanel1.setMinimumSize(new java.awt.Dimension(1368, 659));
        jPanel1.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        squad.setBackground(new java.awt.Color(239, 244, 244));
        squad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        squad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR", "Agreement Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        squad.setGridColor(new java.awt.Color(255, 255, 255));
        squad.setRowHeight(25);
        jScrollPane1.setViewportView(squad);
        if (squad.getColumnModel().getColumnCount() > 0) {
            squad.getColumnModel().getColumn(0).setMinWidth(80);
            squad.getColumnModel().getColumn(0).setPreferredWidth(80);
            squad.getColumnModel().getColumn(0).setMaxWidth(80);
            squad.getColumnModel().getColumn(2).setMinWidth(140);
            squad.getColumnModel().getColumn(2).setPreferredWidth(140);
            squad.getColumnModel().getColumn(2).setMaxWidth(140);
            squad.getColumnModel().getColumn(3).setMinWidth(50);
            squad.getColumnModel().getColumn(3).setPreferredWidth(50);
            squad.getColumnModel().getColumn(3).setMaxWidth(50);
            squad.getColumnModel().getColumn(4).setMinWidth(140);
            squad.getColumnModel().getColumn(4).setPreferredWidth(140);
            squad.getColumnModel().getColumn(4).setMaxWidth(140);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(710, 90, 630, 550);

        jPanel9.setBackground(new java.awt.Color(71, 120, 197));
        jPanel9.setLayout(null);

        parentPanel.setBackground(new java.awt.Color(71, 120, 197));
        parentPanel.setName("parentPanel"); // NOI18N
        parentPanel.setOpaque(false);
        parentPanel.setLayout(new java.awt.CardLayout());

        ForwadPlayer.setOpaque(false);
        ForwadPlayer.setLayout(null);

        jScrollPane12.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        forward.setBackground(new java.awt.Color(71, 120, 197));
        forward.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        forward.setGridColor(new java.awt.Color(120, 168, 252));
        forward.setRowHeight(22);
        jScrollPane12.setViewportView(forward);
        if (forward.getColumnModel().getColumnCount() > 0) {
            forward.getColumnModel().getColumn(0).setMinWidth(75);
            forward.getColumnModel().getColumn(0).setPreferredWidth(75);
            forward.getColumnModel().getColumn(0).setMaxWidth(75);
            forward.getColumnModel().getColumn(2).setMinWidth(130);
            forward.getColumnModel().getColumn(2).setPreferredWidth(130);
            forward.getColumnModel().getColumn(2).setMaxWidth(130);
            forward.getColumnModel().getColumn(3).setMinWidth(50);
            forward.getColumnModel().getColumn(3).setPreferredWidth(50);
            forward.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        ForwadPlayer.add(jScrollPane12);
        jScrollPane12.setBounds(20, 50, 452, 400);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("FORWAD PLAYERS");
        ForwadPlayer.add(jLabel22);
        jLabel22.setBounds(20, 10, 450, 22);

        jButton1.setText("Check List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ForwadPlayer.add(jButton1);
        jButton1.setBounds(20, 480, 130, 30);

        parentPanel.add(ForwadPlayer, "card2");

        Defenders.setOpaque(false);
        Defenders.setLayout(null);

        jScrollPane11.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        defenders.setBackground(new java.awt.Color(71, 120, 197));
        defenders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        defenders.setGridColor(new java.awt.Color(120, 168, 252));
        defenders.setRowHeight(22);
        jScrollPane11.setViewportView(defenders);
        if (defenders.getColumnModel().getColumnCount() > 0) {
            defenders.getColumnModel().getColumn(0).setMinWidth(75);
            defenders.getColumnModel().getColumn(0).setPreferredWidth(75);
            defenders.getColumnModel().getColumn(0).setMaxWidth(75);
            defenders.getColumnModel().getColumn(2).setMinWidth(130);
            defenders.getColumnModel().getColumn(2).setPreferredWidth(130);
            defenders.getColumnModel().getColumn(2).setMaxWidth(130);
            defenders.getColumnModel().getColumn(3).setMinWidth(50);
            defenders.getColumnModel().getColumn(3).setPreferredWidth(50);
            defenders.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        Defenders.add(jScrollPane11);
        jScrollPane11.setBounds(20, 50, 452, 400);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("DEFENDERS");
        Defenders.add(jLabel26);
        jLabel26.setBounds(20, 10, 450, 22);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Check List");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Defenders.add(jButton13);
        jButton13.setBounds(20, 480, 140, 35);

        parentPanel.add(Defenders, "card2");

        RightWingers.setOpaque(false);
        RightWingers.setLayout(null);

        jScrollPane10.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        rightWing.setBackground(new java.awt.Color(71, 120, 197));
        rightWing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rightWing.setGridColor(new java.awt.Color(120, 168, 252));
        rightWing.setRowHeight(22);
        jScrollPane10.setViewportView(rightWing);
        if (rightWing.getColumnModel().getColumnCount() > 0) {
            rightWing.getColumnModel().getColumn(0).setMinWidth(75);
            rightWing.getColumnModel().getColumn(0).setPreferredWidth(75);
            rightWing.getColumnModel().getColumn(0).setMaxWidth(75);
            rightWing.getColumnModel().getColumn(2).setMinWidth(130);
            rightWing.getColumnModel().getColumn(2).setPreferredWidth(130);
            rightWing.getColumnModel().getColumn(2).setMaxWidth(130);
            rightWing.getColumnModel().getColumn(3).setMinWidth(50);
            rightWing.getColumnModel().getColumn(3).setPreferredWidth(50);
            rightWing.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        RightWingers.add(jScrollPane10);
        jScrollPane10.setBounds(20, 50, 452, 400);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("RIGHT WINGERS");
        RightWingers.add(jLabel24);
        jLabel24.setBounds(20, 10, 450, 22);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Check List");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        RightWingers.add(jButton12);
        jButton12.setBounds(20, 480, 140, 35);

        parentPanel.add(RightWingers, "card2");

        MidFiealders.setOpaque(false);
        MidFiealders.setLayout(null);

        jScrollPane9.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        mid.setBackground(new java.awt.Color(71, 120, 197));
        mid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mid.setGridColor(new java.awt.Color(120, 168, 252));
        mid.setRowHeight(22);
        jScrollPane9.setViewportView(mid);
        if (mid.getColumnModel().getColumnCount() > 0) {
            mid.getColumnModel().getColumn(0).setMinWidth(75);
            mid.getColumnModel().getColumn(0).setPreferredWidth(75);
            mid.getColumnModel().getColumn(0).setMaxWidth(75);
            mid.getColumnModel().getColumn(2).setMinWidth(130);
            mid.getColumnModel().getColumn(2).setPreferredWidth(130);
            mid.getColumnModel().getColumn(2).setMaxWidth(130);
            mid.getColumnModel().getColumn(3).setMinWidth(50);
            mid.getColumnModel().getColumn(3).setPreferredWidth(50);
            mid.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        MidFiealders.add(jScrollPane9);
        jScrollPane9.setBounds(20, 50, 452, 400);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("MID FIEALDERS");
        MidFiealders.add(jLabel23);
        jLabel23.setBounds(20, 10, 450, 22);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Check List");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        MidFiealders.add(jButton11);
        jButton11.setBounds(20, 480, 140, 35);

        parentPanel.add(MidFiealders, "card2");

        LeftWingers.setOpaque(false);
        LeftWingers.setLayout(null);

        jScrollPane8.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        leftwing.setBackground(new java.awt.Color(71, 120, 197));
        leftwing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        leftwing.setGridColor(new java.awt.Color(120, 168, 252));
        leftwing.setRowHeight(22);
        jScrollPane8.setViewportView(leftwing);
        if (leftwing.getColumnModel().getColumnCount() > 0) {
            leftwing.getColumnModel().getColumn(0).setMinWidth(75);
            leftwing.getColumnModel().getColumn(0).setPreferredWidth(75);
            leftwing.getColumnModel().getColumn(0).setMaxWidth(75);
            leftwing.getColumnModel().getColumn(2).setMinWidth(130);
            leftwing.getColumnModel().getColumn(2).setPreferredWidth(130);
            leftwing.getColumnModel().getColumn(2).setMaxWidth(130);
            leftwing.getColumnModel().getColumn(3).setMinWidth(50);
            leftwing.getColumnModel().getColumn(3).setPreferredWidth(50);
            leftwing.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        LeftWingers.add(jScrollPane8);
        jScrollPane8.setBounds(20, 50, 452, 400);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("LEFT WINGERS");
        LeftWingers.add(jLabel25);
        jLabel25.setBounds(20, 10, 450, 22);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Check List");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        LeftWingers.add(jButton10);
        jButton10.setBounds(20, 480, 140, 35);

        parentPanel.add(LeftWingers, "card2");

        GoalKeepers.setOpaque(false);
        GoalKeepers.setLayout(null);

        jScrollPane7.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        goalKeeper.setBackground(new java.awt.Color(71, 120, 197));
        goalKeeper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Player ID", "Name", "Position", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        goalKeeper.setGridColor(new java.awt.Color(120, 168, 252));
        goalKeeper.setRowHeight(22);
        jScrollPane7.setViewportView(goalKeeper);
        if (goalKeeper.getColumnModel().getColumnCount() > 0) {
            goalKeeper.getColumnModel().getColumn(0).setMinWidth(75);
            goalKeeper.getColumnModel().getColumn(0).setPreferredWidth(75);
            goalKeeper.getColumnModel().getColumn(0).setMaxWidth(75);
            goalKeeper.getColumnModel().getColumn(2).setMinWidth(130);
            goalKeeper.getColumnModel().getColumn(2).setPreferredWidth(130);
            goalKeeper.getColumnModel().getColumn(2).setMaxWidth(130);
            goalKeeper.getColumnModel().getColumn(3).setMinWidth(50);
            goalKeeper.getColumnModel().getColumn(3).setPreferredWidth(50);
            goalKeeper.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        GoalKeepers.add(jScrollPane7);
        jScrollPane7.setBounds(20, 50, 452, 400);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("GOAL KEEPERS");
        GoalKeepers.add(jLabel27);
        jLabel27.setBounds(20, 10, 450, 22);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Check List");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        GoalKeepers.add(jButton8);
        jButton8.setBounds(20, 480, 140, 35);

        parentPanel.add(GoalKeepers, "card2");

        jPanel9.add(parentPanel);
        parentPanel.setBounds(0, 90, 490, 550);

        jPanel3.setBackground(new java.awt.Color(120, 168, 252));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WHOLE SQUAD");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 181, 30);

        jPanel9.add(jPanel3);
        jPanel3.setBounds(0, 0, 490, 50);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(190, 30, 490, 720);

        Side_Pane.setBackground(new java.awt.Color(23, 35, 51));
        Side_Pane.setLayout(null);

        btn_1.setBackground(new java.awt.Color(41, 57, 80));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });
        btn_1.setLayout(null);

        jPanel12.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_1.add(jPanel12);
        jPanel12.setBounds(0, 0, 3, 44);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Forwad Players");
        btn_1.add(jLabel8);
        jLabel8.setBounds(46, 16, 99, 15);

        Side_Pane.add(btn_1);
        btn_1.setBounds(0, 80, 190, 44);

        btn_2.setBackground(new java.awt.Color(23, 35, 51));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
        });
        btn_2.setLayout(null);

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_2.add(jPanel13);
        jPanel13.setBounds(0, 0, 3, 44);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mid Fiealders");
        btn_2.add(jLabel9);
        jLabel9.setBounds(46, 13, 86, 15);

        Side_Pane.add(btn_2);
        btn_2.setBounds(0, 140, 190, 44);

        btn_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });
        btn_3.setLayout(null);

        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_3.add(jPanel14);
        jPanel14.setBounds(0, 0, 3, 44);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Right Wingers");
        btn_3.add(jLabel10);
        jLabel10.setBounds(46, 13, 89, 15);

        Side_Pane.add(btn_3);
        btn_3.setBounds(0, 200, 190, 44);

        btn_4.setBackground(new java.awt.Color(23, 35, 51));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });
        btn_4.setLayout(null);

        jPanel15.setOpaque(false);
        jPanel15.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_4.add(jPanel15);
        jPanel15.setBounds(0, 0, 3, 44);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Left Wingers");
        btn_4.add(jLabel11);
        jLabel11.setBounds(46, 13, 80, 15);

        Side_Pane.add(btn_4);
        btn_4.setBounds(0, 260, 190, 44);

        btn_5.setBackground(new java.awt.Color(23, 35, 51));
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_5MousePressed(evt);
            }
        });
        btn_5.setLayout(null);

        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_5.add(jPanel16);
        jPanel16.setBounds(0, 0, 3, 44);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Defenders");
        btn_5.add(jLabel12);
        jLabel12.setBounds(46, 13, 64, 15);

        Side_Pane.add(btn_5);
        btn_5.setBounds(0, 320, 190, 44);

        btn_6.setBackground(new java.awt.Color(23, 35, 51));
        btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_6MousePressed(evt);
            }
        });
        btn_6.setLayout(null);

        jPanel17.setOpaque(false);
        jPanel17.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_6.add(jPanel17);
        jPanel17.setBounds(0, 0, 3, 44);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Goal Keepers");
        btn_6.add(jLabel13);
        jLabel13.setBounds(46, 13, 86, 15);

        Side_Pane.add(btn_6);
        btn_6.setBounds(0, 380, 190, 44);

        jPanel1.add(Side_Pane);
        Side_Pane.setBounds(0, 0, 190, 750);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(190, 0, 490, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(71, 120, 197));
        jLabel17.setText("LIST OF ALL PLAYERS ACCORDING TO THEIR ID");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(710, 40, 570, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/minimize2.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1270, 0, 50, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/close2.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1320, 0, 50, 30);

        squadRefresh.setBackground(new java.awt.Color(255, 255, 255));
        squadRefresh.setText("Refresh");
        squadRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squadRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(squadRefresh);
        squadRefresh.setBounds(880, 680, 140, 35);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(710, 680, 140, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MousePressed
        setColor(btn_6);
        jPanel17.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4,btn_5,btn_1}, new JPanel[]{jPanel13,jPanel14,jPanel15,jPanel16,jPanel12});

        parentPanel.removeAll();
        parentPanel.add(GoalKeepers);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_6MousePressed

    private void btn_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MousePressed
        setColor(btn_5);
        jPanel16.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4,btn_1,btn_6}, new JPanel[]{jPanel13,jPanel14,jPanel15,jPanel12,jPanel17});

        parentPanel.removeAll();
        parentPanel.add(Defenders);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_5MousePressed

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        setColor(btn_4);
        jPanel15.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_1,btn_5,btn_6}, new JPanel[]{jPanel13,jPanel14,jPanel12,jPanel16,jPanel17});

        parentPanel.removeAll();
        parentPanel.add(LeftWingers);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_4MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        setColor(btn_3);
        jPanel14.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_1,btn_4,btn_5,btn_6}, new JPanel[]{jPanel13,jPanel12,jPanel15,jPanel16,jPanel17});

        parentPanel.removeAll();
        parentPanel.add(RightWingers);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        setColor(btn_2);
        jPanel13.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_3,btn_4,btn_5,btn_6}, new JPanel[]{jPanel12,jPanel14,jPanel15,jPanel16,jPanel17});

        parentPanel.removeAll();
        parentPanel.add(MidFiealders);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btn_2MousePressed

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        setColor(btn_1);
        jPanel12.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4,btn_5,btn_6}, new JPanel[]{jPanel13,jPanel14,jPanel15,jPanel16,jPanel17});

        parentPanel.removeAll();
        parentPanel.add(ForwadPlayer);
        parentPanel.repaint();
        parentPanel.revalidate();

    }//GEN-LAST:event_btn_1MousePressed

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimize2.png"));
        jLabel15.setIcon(II2);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimizeIn.jpg"));
        jLabel15.setIcon(II2);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/close2.png"));
        jLabel14.setIcon(II);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/closeIn.jpg"));
        jLabel14.setIcon(II);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void squadRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squadRefreshActionPerformed
       
        
        try{
            
            String showTable;
            
            showTable="SELECT `player_id`,`txt_name`,`txt_clubID`,`agri_combo`,`posi_combo`,`txt_dob`,`jersey_number`,`ovrValue` FROM `players` ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            squad.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex);
        }
        

        
        
    }//GEN-LAST:event_squadRefreshActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        
        
        try{
            
            String showTable;
            
            showTable=" SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo`=\"Goal Keeper\" ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            goalKeeper.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
        
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      
        
        new HomeFinalOne().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
            
            String showTable;
            
            showTable=" SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo`=\"Forward\" ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            forward.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        
         try{
            
            String showTable;
            
            showTable=" SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo`=\"Left wing\" ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            leftwing.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
        
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
        try{
            
            String showTable;
            
            showTable=" SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo`=\"Midfielder\" ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
           mid.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
        
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        try{
            
            String showTable;
            
            showTable=" SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo`=\"Right wing\" ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
           rightWing.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
        
        }
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
     
        try{
            
            String showTable;
            
            showTable=" SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo`=\"Defence\" ";
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            defenders.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        
        }catch(Exception ex){
        
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton13ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WholeSquadFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WholeSquadFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WholeSquadFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WholeSquadFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WholeSquadFinalOne().setVisible(true);
            }
        });
    }
    
    
        private void setColor(JPanel pane)
        {
            pane.setBackground(new Color(41,57,80));
        }
        
        private void resetColor(JPanel [] pane, JPanel [] indicators)
        { 
            for(int i=0;i<pane.length;i++)
            {
            pane[i].setBackground(new Color(23,35,51));
            }
            
            for(int i=0;i<indicators.length;i++)
            {
            indicators[i].setOpaque(false);
            }
        }        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Defenders;
    private javax.swing.JPanel ForwadPlayer;
    private javax.swing.JPanel GoalKeepers;
    private javax.swing.JPanel LeftWingers;
    private javax.swing.JPanel MidFiealders;
    private javax.swing.JPanel RightWingers;
    private javax.swing.JPanel Side_Pane;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JPanel btn_5;
    private javax.swing.JPanel btn_6;
    private javax.swing.JTable defenders;
    private javax.swing.JTable forward;
    private javax.swing.JTable goalKeeper;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable leftwing;
    private javax.swing.JTable mid;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTable rightWing;
    private javax.swing.JTable squad;
    private javax.swing.JButton squadRefresh;
    // End of variables declaration//GEN-END:variables
}
