/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FirstXI;

import Home.HomeFinalOne;
import UpdatePlayer.DbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Naseef Nazz
 */
public class FirstXIFinalOne extends javax.swing.JFrame {

   Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    public FirstXIFinalOne() {
        initComponents();
        conn=DbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        wings = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        forward = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        wings1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        mid = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        defence = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        gk = new javax.swing.JTable();
        Side_Pane = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1350, 900));
        setMinimumSize(new java.awt.Dimension(1350, 900));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1350, 890));
        jPanel1.setMinimumSize(new java.awt.Dimension(1350, 890));

        jPanel9.setBackground(new java.awt.Color(71, 120, 197));
        jPanel9.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(120, 168, 252));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST ELEVEN PLAYERS");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 300, 30);

        jPanel9.add(jPanel3);
        jPanel3.setBounds(0, 0, 490, 50);

        jScrollPane7.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        wings.setBackground(new java.awt.Color(71, 120, 197));
        wings.setForeground(new java.awt.Color(255, 255, 255));
        wings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "POS", "NO", "NAME", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        wings.setGridColor(new java.awt.Color(120, 168, 252));
        wings.setRowHeight(35);
        jScrollPane7.setViewportView(wings);
        if (wings.getColumnModel().getColumnCount() > 0) {
            wings.getColumnModel().getColumn(0).setMinWidth(50);
            wings.getColumnModel().getColumn(0).setPreferredWidth(50);
            wings.getColumnModel().getColumn(0).setMaxWidth(50);
            wings.getColumnModel().getColumn(1).setMinWidth(50);
            wings.getColumnModel().getColumn(1).setPreferredWidth(50);
            wings.getColumnModel().getColumn(1).setMaxWidth(50);
            wings.getColumnModel().getColumn(3).setMinWidth(50);
            wings.getColumnModel().getColumn(3).setPreferredWidth(50);
            wings.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel9.add(jScrollPane7);
        jScrollPane7.setBounds(20, 230, 452, 60);
        jScrollPane7.getAccessibleContext().setAccessibleName("");

        jScrollPane8.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        forward.setBackground(new java.awt.Color(71, 120, 197));
        forward.setForeground(new java.awt.Color(255, 255, 255));
        forward.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "POS", "NO", "NAME", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        forward.setGridColor(new java.awt.Color(120, 168, 252));
        forward.setRowHeight(35);
        jScrollPane8.setViewportView(forward);
        if (forward.getColumnModel().getColumnCount() > 0) {
            forward.getColumnModel().getColumn(0).setMinWidth(50);
            forward.getColumnModel().getColumn(0).setPreferredWidth(50);
            forward.getColumnModel().getColumn(0).setMaxWidth(50);
            forward.getColumnModel().getColumn(1).setMinWidth(50);
            forward.getColumnModel().getColumn(1).setPreferredWidth(50);
            forward.getColumnModel().getColumn(1).setMaxWidth(50);
            forward.getColumnModel().getColumn(3).setMinWidth(50);
            forward.getColumnModel().getColumn(3).setPreferredWidth(50);
            forward.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel9.add(jScrollPane8);
        jScrollPane8.setBounds(20, 90, 452, 100);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Right Wing");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(20, 200, 120, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Forwards");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(20, 60, 110, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Left Wing");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(20, 300, 120, 30);

        jScrollPane9.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        wings1.setBackground(new java.awt.Color(71, 120, 197));
        wings1.setForeground(new java.awt.Color(255, 255, 255));
        wings1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "POS", "NO", "NAME", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        wings1.setGridColor(new java.awt.Color(120, 168, 252));
        wings1.setRowHeight(35);
        jScrollPane9.setViewportView(wings1);
        if (wings1.getColumnModel().getColumnCount() > 0) {
            wings1.getColumnModel().getColumn(0).setMinWidth(50);
            wings1.getColumnModel().getColumn(0).setPreferredWidth(50);
            wings1.getColumnModel().getColumn(0).setMaxWidth(50);
            wings1.getColumnModel().getColumn(1).setMinWidth(50);
            wings1.getColumnModel().getColumn(1).setPreferredWidth(50);
            wings1.getColumnModel().getColumn(1).setMaxWidth(50);
            wings1.getColumnModel().getColumn(3).setMinWidth(50);
            wings1.getColumnModel().getColumn(3).setPreferredWidth(50);
            wings1.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel9.add(jScrollPane9);
        jScrollPane9.setBounds(20, 330, 452, 60);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("MidFielders");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(20, 400, 130, 30);

        jScrollPane10.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        mid.setBackground(new java.awt.Color(71, 120, 197));
        mid.setForeground(new java.awt.Color(255, 255, 255));
        mid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "POS", "NO", "NAME", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mid.setGridColor(new java.awt.Color(120, 168, 252));
        mid.setRowHeight(35);
        jScrollPane10.setViewportView(mid);
        if (mid.getColumnModel().getColumnCount() > 0) {
            mid.getColumnModel().getColumn(0).setMinWidth(50);
            mid.getColumnModel().getColumn(0).setPreferredWidth(50);
            mid.getColumnModel().getColumn(0).setMaxWidth(50);
            mid.getColumnModel().getColumn(1).setMinWidth(50);
            mid.getColumnModel().getColumn(1).setPreferredWidth(50);
            mid.getColumnModel().getColumn(1).setMaxWidth(50);
            mid.getColumnModel().getColumn(3).setMinWidth(50);
            mid.getColumnModel().getColumn(3).setPreferredWidth(50);
            mid.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel9.add(jScrollPane10);
        jScrollPane10.setBounds(20, 430, 452, 100);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Defence");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(20, 540, 110, 30);

        jScrollPane11.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        defence.setBackground(new java.awt.Color(71, 120, 197));
        defence.setForeground(new java.awt.Color(255, 255, 255));
        defence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "POS", "NO", "NAME", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        defence.setGridColor(new java.awt.Color(120, 168, 252));
        defence.setRowHeight(35);
        jScrollPane11.setViewportView(defence);
        if (defence.getColumnModel().getColumnCount() > 0) {
            defence.getColumnModel().getColumn(0).setMinWidth(50);
            defence.getColumnModel().getColumn(0).setPreferredWidth(50);
            defence.getColumnModel().getColumn(0).setMaxWidth(50);
            defence.getColumnModel().getColumn(1).setMinWidth(50);
            defence.getColumnModel().getColumn(1).setPreferredWidth(50);
            defence.getColumnModel().getColumn(1).setMaxWidth(50);
            defence.getColumnModel().getColumn(3).setMinWidth(50);
            defence.getColumnModel().getColumn(3).setPreferredWidth(50);
            defence.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel9.add(jScrollPane11);
        jScrollPane11.setBounds(20, 570, 452, 170);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Goal Keeper");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(20, 750, 140, 30);

        jScrollPane12.setBackground(new java.awt.Color(71, 120, 197));
        jScrollPane12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197)));

        gk.setBackground(new java.awt.Color(71, 120, 197));
        gk.setForeground(new java.awt.Color(255, 255, 255));
        gk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "POS", "NO", "NAME", "OVR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gk.setGridColor(new java.awt.Color(120, 168, 252));
        gk.setRowHeight(35);
        jScrollPane12.setViewportView(gk);
        if (gk.getColumnModel().getColumnCount() > 0) {
            gk.getColumnModel().getColumn(0).setMinWidth(50);
            gk.getColumnModel().getColumn(0).setPreferredWidth(50);
            gk.getColumnModel().getColumn(0).setMaxWidth(50);
            gk.getColumnModel().getColumn(1).setMinWidth(50);
            gk.getColumnModel().getColumn(1).setPreferredWidth(50);
            gk.getColumnModel().getColumn(1).setMaxWidth(50);
            gk.getColumnModel().getColumn(3).setMinWidth(50);
            gk.getColumnModel().getColumn(3).setPreferredWidth(50);
            gk.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel9.add(jScrollPane12);
        jScrollPane12.setBounds(20, 780, 452, 60);

        Side_Pane.setBackground(new java.awt.Color(23, 35, 51));
        Side_Pane.setLayout(null);

        btn_1.setBackground(new java.awt.Color(41, 57, 80));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });
        btn_1.setLayout(null);

        jPanel12.setPreferredSize(new java.awt.Dimension(3, 44));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        btn_1.add(jPanel12);
        jPanel12.setBounds(0, 0, 3, 44);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("First XI Table");
        btn_1.add(jLabel8);
        jLabel8.setBounds(46, 16, 84, 15);

        Side_Pane.add(btn_1);
        btn_1.setBounds(0, 80, 190, 44);

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(71, 120, 197));
        jLabel17.setText("UNITED FC'S BEST POSIBLE TEAM ");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/minimize2.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/close2.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(71, 120, 197));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(71, 120, 197));
        jButton5.setText("Generate Team");
        jButton5.setActionCommand("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FirstXI/club logo 4.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("~ Pele");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("\" The More Difficult the victory, the greater hapiness in winning\"");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(272, 272, 272))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(29, 29, 29)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(532, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(140, 140, 140)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Side_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(540, 540, 540)
                                .addComponent(jLabel18)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel19))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(10, 10, 10)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Side_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1350, 910);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        
    }//GEN-LAST:event_btn_1MousePressed

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimizeIn.jpg"));
        jLabel18.setIcon(II2);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        ImageIcon II2 = new ImageIcon(getClass().getResource("/Login/minimize2.png"));
        jLabel18.setIcon(II2);
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/closeIn.jpg"));
        jLabel19.setIcon(II);
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Login/close2.png"));
        jLabel19.setIcon(II);
    }//GEN-LAST:event_jLabel19MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new HomeFinalOne().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        
        try{
            
            String showTable;
            
            showTable="SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue`  FROM `players` WHERE `posi_combo` LIKE 'Forward' ORDER BY `ovrValue` DESC LIMIT 2";
//                      +"AND"+
//                      " WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` ASC LIMIT 2";
            
           
            
            Statement stmt =conn.createStatement();
            
        
            ResultSet rs=stmt.executeQuery(showTable);
            
            
            //please code to view details when the frame opened
            //code works
            forward.setModel(DbUtils.resultSetToTableModel(rs));
            
            
    
            
  
        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex);
        }
        
        try{
            
            String showTable1;
            
            showTable1="SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue`  FROM `players` WHERE `posi_combo` LIKE 'Right wing' ORDER BY `ovrValue` DESC LIMIT 1";
//                      +"AND"+
//                      " WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` ASC LIMIT 2";
            
           
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable1);
            
            
            //please code to view details when the frame opened
            //code works
            wings.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
        try{
            
            String showTable2;
            
            showTable2="SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue`  FROM `players` WHERE `posi_combo` LIKE 'Left wing' ORDER BY `ovrValue` DESC LIMIT 1";
//                      +"AND"+
//                      " WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` ASC LIMIT 2";
            
           
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable2);
            
            
            //please code to view details when the frame opened
            //code works
            wings1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
        try{
            
            String showTable3;
            
            showTable3="SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue` FROM `players` WHERE `posi_combo` LIKE 'Midfielder' ORDER BY `ovrValue` DESC LIMIT 2";
//                      +"AND"+
//                      " WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` ASC LIMIT 2";
            
           
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable3);
            
            
            //please code to view details when the frame opened
            //code works
            mid.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
                try{
            
            String showTable4;
            
            showTable4="SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue`  FROM `players` WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` DESC LIMIT 4";
//                      +"AND"+
//                      " WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` ASC LIMIT 2";
            
           
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable4);
            
            
            //please code to view details when the frame opened
            //code works
            defence.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
        try{
            
            String showTable5;
            
            showTable5="SELECT `player_id`, `txt_name`,`txt_clubID`,`posi_combo`,`jersey_number`,`ovrValue`  FROM `players` WHERE `posi_combo` LIKE 'Goal Keeper' ORDER BY `ovrValue` DESC LIMIT 1";
//                      +"AND"+
//                      " WHERE `posi_combo` LIKE 'Defence' ORDER BY `ovrValue` ASC LIMIT 2";
            
           
            
            Statement stmt =conn.createStatement();
            
          //  pst=conn.prepareStatement(showTable);
            ResultSet rs=stmt.executeQuery(showTable5);
            
            
            //please code to view details when the frame opened
            //code works
            gk.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
            
        }        
        
        
        //to retrive the number and name at left side
        
        
       
           
          
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstXIFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstXIFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstXIFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstXIFinalOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstXIFinalOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Side_Pane;
    private javax.swing.JPanel btn_1;
    private javax.swing.JTable defence;
    private javax.swing.JTable forward;
    private javax.swing.JTable gk;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable mid;
    private javax.swing.JTable wings;
    private javax.swing.JTable wings1;
    // End of variables declaration//GEN-END:variables
}
